import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('배포용 매뉴얼', () => {
  it('사용자·운영자 HTML이 주요 안내를 담는다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(user).toContain('한 턴의 순서');
    expect(user).toContain('지금 구현된 것');
    expect(user).toContain('첫 판 따라하기');
    expect(user).toContain('케이스북');
    expect(user).toContain('안정형');
    expect(user).toContain('70%');
    expect(user).toContain('C18');
    expect(user).toContain('진행');
    expect(user).toContain('보류');
    expect(user).toContain('한도까지');
    expect(user).toContain('C21');
    expect(user).toContain('지금 판에 바로');
    expect(user).toContain('지금 판에 반영');
    expect(user).toContain('이 브라우저에 저장');
    expect(user).toContain('예금·채권 매수는 됩니다');
    expect(user).toContain('정산 요약');
    expect(user).toContain('C22');
    expect(user).toContain('3별의 성향 정렬');
    expect(user).toContain('즉시 매도해 지급');
    expect(user).toContain('C19');
    expect(user).toContain('C20');
    expect(user).toContain('도착 칸이');
    expect(user).toContain('목표에 가까워진 적립가');
    expect(user).toContain('목표의 95%');
    expect(user).toContain('C23');
    expect(user).toContain('리밸런싱 목표 위험비중');
    expect(operator).toContain('구현된 기능');
    expect(operator).toContain('QA 케이스 매트릭스');
    expect(operator).toContain('vercel');
    expect(operator).toContain('pension-road.vercel.app');
    expect(operator).toContain('policy-rules.json');
    expect(operator).toContain('pages.yml');
    expect(operator).toContain('비중을 더 키우지 않는');
    expect(operator).toContain('Q17');
    expect(operator).toContain('Q18');
    expect(operator).toContain('Q19');
    expect(operator).toContain('Q20');
    expect(operator).toContain('Q21');
    expect(operator).toContain('nearGoalRate');
    expect(user).toContain('대기자금은 0원');
    expect(user).toContain('먼저 납입하기');
    expect(user).toContain('위험자산 충격');
    expect(operator).toContain('goalMonthly');
    expect(operator).toContain('Q22');
    expect(operator).toContain('Q23');
    expect(user).toContain('교육용 가상 금리');
    expect(user).toContain('2~3회');
    expect(user).toContain('다음 턴 신호');
    expect(user).toContain('신호는 예측이 아니라');
    expect(user).toContain('C24');
    expect(user).toContain('C25');
    expect(user).not.toContain('3~10턴 사이 2회');
    expect(operator).toContain('market-shocks.json');
    expect(user).toContain('C27');
    expect(user).toContain('C28');
    expect(user).toContain('캐릭터 표시');
    expect(user).toContain('기본 끔');
    expect(user).toContain('가장 아슬아슬했던 턴');
    expect(operator).toContain('Q30');
    expect(operator).toContain('Q32');
    expect(operator).toContain('Q35');
    expect(operator).toContain('Q36');
    expect(operator).toContain('token3d.ts');
    expect(user).toContain('말 모양');
    expect(operator).toContain('settings.characters');
    expect(operator).toContain('avatars.ts');
    expect(operator).toContain('sound.ts');
    expect(operator).toContain('regime-engine.ts');
    expect(operator).toContain('balance-gate');
    expect(operator).toContain('Q24');
    expect(operator).toContain('Q25');
    expect(operator).toContain('Q26');
    expect(user).toContain('속보 카드');
    expect(user).toContain('칸 설명 보기');
    expect(user).toContain('정산 장면');
    expect(user).toContain('목표 게이지');
    expect(user).toContain('C26');
    expect(operator).toContain('news-flash.ts');
    expect(operator).toContain('hud.ts');
    expect(operator).toContain('Q27');
    expect(operator).toContain('Q28');
    expect(operator).toContain('Q29');
  });

  it('2026-09-06 현행화: 구현 기준일·운영 태그·모듈 목록·기능 목록이 최신이다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(operator).toContain('구현 기준 2026-09-06');
    expect(operator).not.toContain('구현 기준 2026-08-17');
    expect(operator).not.toContain('2026-08-17)');
    expect(operator).toContain('prod-2026-09-06-token-3d');
    expect(operator).toContain('운영 태그와 되돌리기');
    expect(operator).toContain('Promote');
    expect(operator).toContain('git revert -m 1');
    expect(operator).toContain('board.ts');
    expect(operator).toContain('dice.ts');
    expect(operator).toContain('market-view.ts');
    expect(operator).toContain('settlement-engine.ts');
    expect(operator).toContain('2.5D 말');
    expect(operator).toContain('연출 코어');
    expect(operator).toContain('회귀 231개');
    expect(operator).toContain('Q1~Q46');
    expect(operator).not.toContain('Q1~Q45');
    expect(operator).not.toContain('Q1~Q16');
    expect(operator).not.toContain('Q1~Q36');
    expect(user).toContain('구현 기준 2026-09-06');
    expect(user).not.toContain('구현 기준 2026-08-17');
    expect(user).toContain('12턴 IRP 곡선');
    expect(user).toContain('효과음 9종');
    expect(user).toContain('설정(동작 줄이기·캐릭터 표시·효과음·"그대로 둔 나" 비교)');
  });

  it('묶음 A 현행화: 시장 먼저 순서·칸 효과·환급·행동 2회·고스트가 두 매뉴얼에 있다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    // 사용자: 순서·규칙
    expect(user).toContain('시장이 먼저 움직입니다');
    expect(user).toContain('내 IRP에 반영');
    expect(user).toContain('도착 칸 효과');
    expect(user).toContain('연말정산 칸을 지날 때');
    expect(user).toContain('환급 대기');
    expect(user).toContain('행동 1/2 하기');
    expect(user).toContain('스포트라이트');
    expect(user).toContain('은퇴 전망대');
    expect(user).toContain('그대로 둔 나');
    expect(user).toContain('판단의 값어치');
    expect(user).toContain('고스트 격파');
    expect(user).toContain('턴 시작 → 시장 반영 → 내 행동 후');
    expect(user).not.toContain('아직 잔고에는 안 들어갑니다');
    expect(user).not.toContain('거래 없이 이번 턴 시장만 반영합니다');
    for (const id of ['C30', 'C31', 'C32', 'C33', 'C34', 'C35', 'C36', 'C37']) expect(user).toContain(`${id}.`);
    // 운영자: 모듈·저장·QA·게이트·절차
    expect(operator).toContain('tile-effects.ts');
    expect(operator).toContain('ghost.ts');
    expect(operator).toContain('tile-effects-view.ts');
    expect(operator).toContain('settings.ghost');
    expect(operator).toContain('버전 4');
    expect(operator).toContain('pendingTaxCredit');
    expect(operator).toContain('newsChaser');
    expect(operator).toContain('turn-order.test.ts');
    expect(operator).toContain('OUTLOOK_FORKS');
    expect(operator).toContain('EXTRA_LIFE_EVENT_CAP');
    expect(operator).toContain('prod-2026-09-06-bundle-a');
    expect(operator).toContain('필수 절차');
    for (const id of ['Q37', 'Q38', 'Q39', 'Q40', 'Q41', 'Q42', 'Q43', 'Q44', 'Q45']) expect(operator).toContain(`<td>${id}</td>`);
    expect(operator).not.toContain('브리핑 → 생활사건 → 행동 1회 → 정산');
    expect(operator).not.toContain('WebAudio 합성 8종');
  });

  it('매도·교체 선택 보정 핫픽스: 두 매뉴얼이 규칙과 QA 케이스를 담는다', () => {
    const user = readFileSync('public/user-manual.html', 'utf8');
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(user).toContain('10만 원 이상 보유한 상품만');
    expect(user).toContain('첫 보유 상품으로 자동으로 넘어갑니다');
    expect(user).toContain('위험 상품을 안전자산으로 옮기는 가장 빠른 길');
    expect(user).toContain('C38.');
    expect(operator).toContain('action-form.ts');
    expect(operator).toContain('pickHeldProduct');
    expect(operator).toContain('tradeBlockReason');
    expect(operator).toContain('<td>Q46</td>');
    expect(operator).toContain('prod-2026-09-06-sell-switch-fix');
  });

  it('다이어그램 5장이 배포 폴더에 있고 운영자 매뉴얼이 링크한다', () => {
    const operator = readFileSync('public/operator-manual.html', 'utf8');
    expect(operator).toContain('href="./diagrams/"');
    const index = readFileSync('public/diagrams/index.html', 'utf8');
    for (const name of ['architecture', 'turn-workflow', 'seed-dataflow', 'game-lifecycle', 'action-sequence']) {
      expect(index).toContain(`./${name}.html`);
      const html = readFileSync(`public/diagrams/${name}.html`, 'utf8');
      expect(html).toContain('<svg');
      expect(JSON.parse(readFileSync(`docs/diagrams/${name}.json`, 'utf8')).meta.quality_profile).toBe('showcase');
    }
  });
});
